name: Example
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v0
      - uses: matlab-actions/run-tests@v0
        with:
          source-folder: source
          code-coverage-cobertura: coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta-beta-beta-beta
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
        with:
          file: coverage.xml
